version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: project3a_class_image
    container_name: flask-blog
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"